on: 
  push:
    branches:
      - master

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_VERSION: 1.0.0
    steps:
      ## 自动发布
      #- uses: rymndhng/release-on-push-action@master
      #  with:
      #    bump_version_scheme: minor
      #    tag_prefix: v
      #    release_name: "Release <RELEASE_VERSION>"

      # .envrc发布
      - name: Checkout
        uses: actions/checkout@main


      - name: Install babashka
        run: curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install && chmod +x install && ./install

      - name: Install direnv
        run: sudo apt install -y direnv

      - name: Run tests
        run: make test && make dryrun


