name: Releases

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Get current date and time
        id: get_datetime
        run: echo "::set-output name=DATETIME::$(date -u +'%Y%m%d%H%M%S')"

      - name: Create a new tag
        id: create_tag
        run: |
          TAG_NAME="release-${{ steps.get_datetime.outputs.DATETIME }}"
          echo "::set-output name=TAG_NAME::$TAG_NAME"
          git tag $TAG_NAME
          git push --tags

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.REPOS_WORKFLOW_TOKEN }}
          tag: ${{ steps.create_tag.outputs.TAG_NAME }}
          name: Release ${{ steps.create_tag.outputs.TAG_NAME }}
          body: |
            Automatic release created on ${{ steps.get_datetime.outputs.DATETIME }}
          draft: false
          prerelease: false
